language: java
jdk:
  - oraclejdk8
services:
  - docker
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - mvn docker:build
  - docker push $DOCKER_USERNAME/spring-boot-k8s-seed
