---
apiVersion: v1
kind: Namespace
metadata:
  name: spring-boot
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-config
  namespace: spring-boot
data:
  application.yml: |-
    my:
       servers:
           - http://dev.bar.com
           - http://foo.bar.com
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-boot-deployment
  namespace: spring-boot
spec:
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: spring-boot-config
      containers:
      - name: spring-boot-container
        image: danielpacak/spring-boot-k8s-seed:latest
        env:
        - name: SPRING_CONFIG_LOCATION
          value: /etc/config/application.yml
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  namespace: spring-boot
spec:
  selector:
    app: spring-boot
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
